# Generated by Django 5.2.7 on 2025-11-12 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Producto Defectuoso'), ('WRONG_ITEM', 'Producto Incorrecto'), ('NOT_AS_DESCRIBED', 'No Como se Describió'), ('DAMAGED_SHIPPING', 'Dañado en Envío'), ('CHANGED_MIND', 'Cambio de Opinión'), ('SIZE_ISSUE', 'Problema de Talla/Tamaño'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(help_text='Descripción detallada del motivo de devolución')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad a devolver')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completada')], default='REQUESTED', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas del administrador')),
                ('attachment', models.FileField(blank=True, help_text='Foto del producto dañado, etc.', null=True, upload_to='returns/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='sales.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-requested_at'],
            },
        ),
    ]
