# Generated by Django 5.2.7 on 2025-11-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo (Pago contra entrega)'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Tarjeta de crédito')], default='CASH', max_length=10),
        ),
    ]
