# Generated by Django 5.2.7 on 2025-11-13 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, help_text='Tiempo de garantía en meses', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
